id: IF42A0A72
legacy_id: P000619
ocr_import_info:
  bdrc_scan_id: W30175
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T02:10:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:23:30.554198+00:00'
last_modified: 2022-09-03 19:24:05.019352
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30175
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30175
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པ་ལེགས་པར་བཤད་པ་རིན་པོ་ཆེའི་བང་མཛོད།
  author: གཡག་སྟོན་སངས་རྒྱས་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.7312623255286147
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I5958:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5958
      total_pages: 422
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5958.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7453747770617771
    legacy_id: v002
  I5957:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5957
      total_pages: 790
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5957.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7236415719808974
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
