id: P000619
initial_creation_type: ocr
source_metadata:
  id: bdr:W30175
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པ་ལེགས་པར་བཤད་པ་རིན་པོ་ཆེའི་བང་མཛོད
  author: ''
  volumes: ''
