id: P000619
initial_creation_type: ocr
source_metadata:
  id: bdr:W30175
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པ་ལེགས་པར་བཤད་པ་རིན་པོ་ཆེའི་བང་མཛོད
  author: ''
  volumes:
    2c0c904fc1ae442dafdf19ffb2cbcfb7:
      image_group_id: I5957
      title: ''
      volume_number: 1
      total_pages: 790
      base_file: v001.txt
    8dd5044d827141bba481d81aa201de43:
      image_group_id: I5958
      title: ''
      volume_number: 2
      total_pages: 422
      base_file: v002.txt
